### ISSUE TITLE
modules/unitframes/layout/layout.lua:1278: attempt to index local 'unit' (a nil value)

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#22]
[string "@Interface/AddOns/LUI/modules/unitframes/layout/layout.lua"]:1278: in function Power'
[string "@Interface/AddOns/LUI/modules/unitframes/options/toggle.lua"]:838: in function ApplySettings'
[string "@Interface/AddOns/LUI/modules/unitframes/options/toggle.lua"]:1035: in function Refresh'
[string "@Interface/AddOns/LUIOptions/LUIOptions.lua"]:117: in function <Interface/AddOns/LUIOptions/LUIOptions.lua:111>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:827: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function Fire'
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ns/Ace3/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

**Comment by FireSiku** [comment]
Resolved in Alpha 21
