### ISSUE TITLE
4x ...face/AddOns/LUI/modules/unitframes/layout/layout.lua:269: bad argument #1 to 'SetText' (Usage: self:SetText([text]))

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#23]
[string "=[C]"]: in function SetText'
[string "@Interface/AddOns/LUI/modules/unitframes/layout/layout.lua"]:269: in function <...face/AddOns/LUI/modules/unitframes/layout/layout.lua:208>
[string "@Interface/AddOns/LUI/api/oUF11/elements/health.lua"]:198: in function func'
[string "@Interface/AddOns/LUI/api/oUF11/ouf.lua"]:201: in function `UpdateAllElements'
[string "@Interface/AddOns/LUI/api/oUF11/ouf.lua"]:243: in function <Interface/AddOns/LUI/api/oUF11/ouf.lua:238>
[string "=(tail call)"]: ?

Locals:
(temporary) = FontString {
 0 = <userdata>
 color = "Individual"
 colorIndividual = <table> {
 }
 Enable = false
 ShowAlways = true
 ShowDead = false
 Format = "Absolut Short"
}
(temporary) = false

**Comment by FireSiku** [comment]
Fixed with 2210a-7
Blizzard no longer allow nil as a value for SetText.

Changed all instances of SetText() to SetText("") (empty _strings_ are okay)
