### ISSUE TITLE
Stuttering information

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#24]
["1"] = "Stuttering Information:",
["2"] = "An addon feature, script is using: _G.UpdateAddOnMemoryUsage()",
["3"] = "",
["4"] = "Description: Calculates memory usage of addons",
["5"] = "",
["6"] = "You may first: disable the addon feature that uses the functionality.",
["7"] = "Second: disable a script which are using the function call: _G.UpdateAddOnMemoryUsage().",
["8"] = "",
["9"] = "Callstack for Debug:",
["10"] = "[string "@Interface/AddOns/LUI/modules/InfoText/memory.lua"]:48: in function `?'",
["11"] = "[string "@Interface/AddOns/LUI/modules/InfoText/infotext.lua"]:92: in function <Interface/AddOns/LUI/modules/InfoText/infotext.lua:87>",

**Comment by FireSiku** [comment]
This function is not called every time the Memory module is updated anymore.
We're now letting WoW handle routinely updating the usage, but it can be forced by using right click.
Closed with Alpha 17
