### ISSUE TITLE
31x Interface/AddOns/LUI/modules/InfoText/fps.lua:76: attempt to perform arithmetic on upvalue 'GRADIENT_LAG_TOLERANCE' (a nil value)

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#26]
[string "@Interface/AddOns/LUI/modules/InfoText/fps.lua"]:76: in function `OnTooltipShow'
[string "@Interface/AddOns/LUI/modules/InfoText/infotext.lua"]:267: in function <Interface/AddOns/LUI/modules/InfoText/infotext.lua:259>

Locals:
GameTooltip = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = Frame {
 }
 SetShapeshift = <function> defined =[C]:-1
 updateTooltipTimer = 0.113000
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 comparing = false
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 waitingForData = false
 SetPetAction = <function> defined =[C]:-1
 Center = Texture {
 }
 shoppingTooltips = <table> {
 }
 BottomEdge = Texture {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = GameTooltipTextLeft1 {
 }
 backdropInfo = <table> {
 }
 BottomRightCorner = Texture {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 BottomOverlay = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 textRight1Font = "GameTooltipHeaderText"
 TopLeftCorner = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 NineSlice = Frame {
 }
 textLeft2Font = "GameTooltipText"
 TopEdge = Texture {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetAction = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 needsReset = true
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
}
fps = 127
r = 0
g = 1
b = 0
down = 1.117107
up = 0.163619
lagHome = 21
lagWorld = 25
(*temporary) = <function> defined @Interface/AddOns/LUI/api/colors.lua:243
(*temporary) = <table> {
 defaults = <table> {
 }
 NewInputNumber = <function> defined @Interface/AddOns/LUI/api/devapi.lua:998
 Profiler = <table> {
 }
 OnInstall = <function> defined @Interface/AddOns/LUI/init.lua:142
 otherFaction = "Alliance"
 playerFullName = "Evilhardware-Blackmoore"
 NewWidth = <function> defined @Interface/AddOns/LUI/api/devapi.lua:1044
 NewEnable = <function> defined @Interface/AddOns/LUI/api/devapi.lua:873
 SecureHook = <function> defined @Interface/AddOns/LUI/libs/AceHook-3.0/AceHook-3.0.lua:335
 V4Scale = <function> defined @Interface/AddOns/LUI/api/utils.lua:222
 defaultModulePrototype = <table> {
 }
 CopyTable = <function> defined @Interface/AddOns/LUI/api/utils.lua:138
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/LUI/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 NewPosY = <function> defined @Interface/AddOns/LUI/api/devapi.lua:1024
... (14 Zeilen verbleibend)

**Comment by FireSiku** [comment]
Fixed in 2210a-5
