### ISSUE TITLE
infotext/infotip.lua:181: attempt to call method 'SetBackdrop' (a nil value)

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#41]
[string "@Interface/AddOns/LUI/modules/infotext/infotip.lua"]:181: in function `AddSlider'
[string "@Interface/AddOns/LUI/modules/infotext/infotip.lua"]:103: in function `NewLine'
[string "@Interface/AddOns/LUI/modules/infotext/friends.lua"]:157: in function `CreateBNFriend'
[string "@Interface/AddOns/LUI/modules/infotext/friends.lua"]:268: in function `DisplayBNFriends'
[string "@Interface/AddOns/LUI/modules/infotext/friends.lua"]:568: in function `OnEnter'
[string "@Interface/AddOns/LUI/modules/InfoText/infotext.lua"]:264: in function <Interface/AddOns/LUI/modules/InfoText/infotext.lua:260>

Locals:
self = <table> {
 OnLineEnter = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:156
 ApplyBackdropColors = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:197
 AddSlider = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:177
 OnLineLeave = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:162
 OnLineScroll = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:149
}
newtip = LUIInfo_FriendsInfotip {
 BottomLeftCorner = Texture {
 }
 UpdateSlider = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:132
 bcIndex = 0
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 broadcast = LUIInfo_FriendsInfotipLine2 {
 }
 UpdateTooltip = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:123
 totalLines = 69
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 GetSliderOffset = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:119
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 BNFriends = <table> {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 AddSeparator = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:109
 minWidth = 90
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 sep = LUIInfo_FriendsInfotipLine1 {
 }
 maxHeight = 50
 Friends = <table> {
 }
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 FriendsBC = <table> {
 }
 maxLines = 68
 BottomEdge = Texture {
 }
 SetWidth = <function> defined =[C]:-1
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 0 = <userdata>
 Center = Texture {
 }
 NewLine = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:84
 BottomRightCorner = Texture {
 }
 infotext = <table> {
 }
 maxWidth = 421.144867
 TopEdge = Texture {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 bnIndex = 67
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
}
slider = Slider {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = Slider {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Buttons\UI-SliderBar-Background"
 tileSize = 8
 edgeFile = "Buttons\UI-SliderBar-Border"
 edgeSize = 8
 tile = true
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
SLIDER_WIDTH = 16

**Comment by FireSiku** [comment]
Resolved in Alpha 36
