### ISSUE TITLE
LUI modules raidmenu

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#44]
[string "=[C]"]: in function `unpack'
[string "@Interface/AddOns/LUI/modules/raidmenu/raidmenu.lua"]:290: in function `SetColors'
[string "@Interface/AddOns/LUI/modules/artwork/themes.lua"]:48: in function `Refresh_Colors'
[string "@Interface/AddOns/LUI/modules/artwork/themes.lua"]:40: in function `ApplyTheme'
[string "@Interface/AddOns/LUI/modules/artwork/themes.lua"]:877: in function <Interface/AddOns/LUI/modules/artwork/themes.lua:870>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:827: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:432: in function <...ns/Ace3/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua:423>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua"]:351: in function <...3/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua:341>

**Comment by FireSiku** [comment]
Fixed in Alpha 36
