### ISSUE TITLE
infotext friends

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#49]
1x Interface/AddOns/LUI/modules/infotext/friends.lua:295: attempt to concatenate field 'areaName' (a nil value)
[string "@Interface/AddOns/LUI/modules/infotext/friends.lua"]:295: in function `DisplayBNFriends'
[string "@Interface/AddOns/LUI/modules/infotext/friends.lua"]:568: in function `OnEnter'
[string "@Interface/AddOns/LUI/modules/InfoText/infotext.lua"]:268: in function <Interface/AddOns/LUI/modules/InfoText/infotext.lua:264>

Locals:
self = <table> {
}
classIconWidth = 13.000001
nameColumnWidth = 166.802597
noteColumnWidth = 148.382675
gameColumnWidth = 0
levelColumnWidth = 15.349931
factionIconWidth = 0
zoneColumnWidth = 214.899048
total = 195
bnetOnline = 97
fav = 2
favOnline = 1
favOffset = 1
(for index) = 22
(for limit) = 97
(for step) = 1
i = 22
offset = 1
acc = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "|Kq148|k"
 battleTag = "Sunnie#2316"
 note = ""
 rafLinkType = 0
 bnetAccountID = 93
 appearOffline = false
 customMessage = ""
 lastOnlineTime = 1667676882
 customMessageTime = 0
 isAFK = false
 isBattleTagFriend = true
}
game = <table> {
 isGameAFK = false
 clientProgram = "WoW"
 characterName = "Narlie"
 isGameBusy = false
 factionName = "Alliance"
 playerGuid = "Player-4440-0139830F"
 wowProjectID = 11
 gameAccountID = 309
 realmID = 4440
 isInCurrentRegion = true
 hasFocus = true
 canSummon = false
 isWowMobile = false
 regionID = 3
 className = "Priest"
 richPresence = "Wrath of the Lich King Classic - Everlook"
 characterLevel = 79
 raceName = "Dwarf"
 isOnline = true
}
btagString = "|cff82c5ff|Kq148|k|r"
statusString = ""
bnfriend = LUIInfo_FriendsInfotipLine24 {
 0 = <userdata>
 note = FontString {
 }
 index = 22
 zone = FontString {
 }
 class = Texture {
 }
 ResetHeight = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:76
 unit = "Narlie"
 AddTexture = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:44
 AddHighlight = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:72
 gameText = FontString {
 }
 accountID = 93
 accountName = "|Kq148|k"
 SetClassIcon = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:52
 hasBroadcast = false
 AddFontString = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:58
 name = FontString {
 }
 faction = Texture {
 }
 lastOnline = 1667676882
 client = "WoW"
 level = FontString {
 }
}
class = "PRIEST"
nameString = "|cffe6e6e6Narlie|r"
realmString = "|cffffc400 - |r"
(*temporary) = <function> defined =[C]:-1
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "|cffffc400 - |r"
(*temporary) = "|c%s%s|r"
(*temporary) = "ffffc400"
(*temporary) = "attempt to concatenate field 'areaName' (a nil value)"
infotip = LUIInfo_FriendsInfotip {
 BottomLeftCorner = Texture {
 }
 UpdateSlider = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:132
 bcIndex = 0
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 broadcast = LUIInfo_FriendsInfotipLine2 {
 }
 UpdateTooltip = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:123
 totalLines = 70
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 GetSliderOffset = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:119
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 BNFriends = <table> {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 AddSeparator = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:109
 minWidth = 90
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 sep = LUIInfo_FriendsInfotipLine1 {
 }
 maxHeight = 50
 Friends = <table> {
 }
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 FriendsBC = <table> {
 }
 maxLines = 68
 BottomEdge = Texture {
 }
 SetWidth = <function> defined =[C]:-1
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 0 = <userdata>
 Center = Texture {
 }
 NewLine = <function> defined @Interface/AddOns/LUI/modules/infotext/infotip.lua:84
 BottomRig

**Comment by FireSiku** [comment]
Alpha 29
