### ISSUE TITLE
modules/tooltip/tooltip.lua:544: Usage: HookScript(object, method, [handler]): You can only hook a script on a frame object

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#62]
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:143: in function <Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:366: in function `HookScript'
[string "@Interface/AddOns/LUI/modules/tooltip/tooltip.lua"]:544: in function <Interface/AddOns/LUI/modules/tooltip/tooltip.lua:525>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by FireSiku** [comment]
Fixed in 2211-1
