### ISSUE TITLE
modules/tooltip/tooltip.lua:323: attempt to call method 'SetBackdropColor' (a nil value)

### ISSUE THREAD

**Issue by Pahn1988** [FireSiku/LUI#64]
[string "@Interface/AddOns/LUI/modules/tooltip/tooltip.lua"]:323: in function `SetBorderColor'
[string "@Interface/AddOns/LUI/modules/tooltip/tooltip.lua"]:498: in function <Interface/AddOns/LUI/modules/tooltip/tooltip.lua:408>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:479: in function <...nterface/AddOns/Details/classes/container_actors.lua:473>
[string "@Interface/AddOns/Details/classes/container_actors.lua"]:617: in function `PegarCombatente'
[string "@Interface/AddOns/Details/core/parser.lua"]:1802: in function <Interface/AddOns/Details/core/parser.lua:1771>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?

Locals:
Skipped (In Encounter)

**Comment by FireSiku** [comment]
Fixed in 2211-1
